import { Fragment, useState } from 'react';
import { DRIVER_FIELDS, EMPTY_DRIVER, MAX_DRIVERS } from '../../utils/constants.js';
import { validateField, findDuplicateLicenseNumberIndexes } from '../../utils/validators.js';
import OperatingHoursPicker from './OperatingHoursPicker.jsx';

// Summary columns shown directly in each row while editing; every other
// field is always shown in the details panel underneath the row, so the
// table never needs horizontal scrolling.
const SUMMARY_KEYS = ['role', 'firstName', 'lastName', 'email', 'phone'];

/**
 * Editable table for manually adding driver rows to a request.
 * `drivers` / `setDrivers` are lifted state from the parent (NewRequest page).
 */
export default function DriverTable({
  drivers,
  setDrivers,
  readOnly = false,
  filesEditable,
  forceValidate = false,
  skipFileRequiredValidation = false,
  showOperationsFields = false,
}) {
  const canEditFiles = filesEditable ?? !readOnly;
  const [touched, setTouched] = useState({});
  // Files rejected outright at selection time (wrong extension) - kept
  // separate from `touched`/validateField so the row's data never even
  // holds the invalid file; the rejection reason still surfaces inline.
  const [fileRejections, setFileRejections] = useState({});

  const hasChangeSummaries = readOnly && drivers.some((d) => d.changeSummary);
  const hasDriverStatus = readOnly && drivers.some((d) => d.driverStatus);
  // Username is assigned by AD after the fact, so it's not a field the
  // requester fills in - only show that column once a value actually exists.
  // The three Operations-only fields (Group/Customer, Driver Class,
  // Operating Hours) are never shown to requesters - they are completed by
  // Operations during the Processing stage, and staff-facing views opt in
  // via showOperationsFields. Document uploads are shown inline only while
  // editing - completed requests list them via AttachmentsList instead.
  const visibleFields = DRIVER_FIELDS.filter((f) => {
    if (f.autoGenerated) return readOnly;
    if (f.hiddenFromRequester && !showOperationsFields) return false;
    if (f.hiddenFromRequester && !readOnly) return false;
    if (f.type === 'file' && readOnly) return false;
    return true;
  });

  const summaryFields = visibleFields.filter((f) => SUMMARY_KEYS.includes(f.key));
  const detailFields = visibleFields.filter((f) => !SUMMARY_KEYS.includes(f.key));

  function addRow() {
    if (drivers.length >= MAX_DRIVERS) return;
    setDrivers([...drivers, { ...EMPTY_DRIVER }]);
  }

  function removeRow(idx) {
    setDrivers(drivers.filter((_, i) => i !== idx));
  }

  function updateCell(idx, key, value) {
    const next = drivers.slice();
    next[idx] = { ...next[idx], [key]: value };
    setDrivers(next);
  }

  function removeAll() {
    setDrivers([]);
  }

  function markTouched(idx, key) {
    setTouched((prev) => ({ ...prev, [`${idx}:${key}`]: true }));
  }

  function cellError(idx, f, row) {
    if (readOnly) return null;
    // Editing a returned request doesn't re-populate file inputs (browsers
    // won't let us pre-fill them from an existing upload) - the original
    // documents are still attached server-side, so don't force a re-upload.
    if (skipFileRequiredValidation && f.type === 'file') return null;
    const isTouched = forceValidate || touched[`${idx}:${f.key}`];
    if (!isTouched) return null;
    const fieldError = validateField(f, row[f.key], { requireCreateFields: true });
    if (fieldError) return fieldError;
    // Flag same-table duplicates immediately, rather than only on submit -
    // mirrors the backend's within-batch uniqueness check.
    if (f.key === 'licenseNumber' && findDuplicateLicenseNumberIndexes(drivers).has(idx)) {
      return 'Driver License/ID/IQAMA Number is duplicated within this submission';
    }
    return null;
  }

  // The browser's `accept` attribute is only a filter hint - the OS file
  // picker still lets people choose "All Files", so wrong-type uploads
  // (e.g. an Excel sheet where a license/ID/photo is expected) are rejected
  // here outright rather than being stored and merely flagged as invalid.
  function handleFileSelect(idx, f, file) {
    const key = `${idx}:${f.key}`;
    markTouched(idx, f.key);

    if (file && f.allowedExtensions?.length) {
      const extension = file.name.split('.').pop()?.toLowerCase();
      if (!f.allowedExtensions.includes(extension)) {
        const message = `${f.label} must be one of the following file types: ${f.allowedExtensions.join(', ')}`;
        setFileRejections((prev) => ({ ...prev, [key]: message }));
        // The OS file picker's "All Files" option can bypass the `accept`
        // filter, so a rejected file is common enough to need a message
        // impossible to miss - not just a small inline note under the row.
        window.alert(`"${file.name}" was not attached.\n\n${message}`);
        return;
      }
    }

    setFileRejections((prev) => {
      if (!(key in prev)) return prev;
      const next = { ...prev };
      delete next[key];
      return next;
    });
    updateCell(idx, f.key, file || '');
  }

  function renderInput(idx, f, row) {
    const error = cellError(idx, f, row);
    const inputBorder = error ? 'border-red-400' : 'border-gray-300';

    if (f.fixed) {
      return <p className="text-sm text-gray-700 py-1">{row[f.key] || f.defaultValue || '-'}</p>;
    }

    if (f.key === 'operatingHours') {
      return (
        <div className="min-w-[240px]">
          <OperatingHoursPicker value={row[f.key]} onChange={(v) => updateCell(idx, f.key, v)} />
        </div>
      );
    }

    if (f.type === 'select') {
      return (
        <div>
          <select
            required={f.required}
            value={row[f.key] || ''}
            onChange={(e) => updateCell(idx, f.key, e.target.value)}
            onBlur={() => markTouched(idx, f.key)}
            className={`w-full border rounded px-2 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-primary-500 ${inputBorder}`}
          >
            <option value="">Select...</option>
            {f.options.map((opt) => (
              <option key={opt} value={opt}>
                {opt}
              </option>
            ))}
          </select>
          {error && <p className="text-[11px] text-red-500 mt-0.5">{error}</p>}
        </div>
      );
    }

    if (f.type === 'file') {
      const rejection = fileRejections[`${idx}:${f.key}`];
      return (
        <div>
          {row[f.key] ? (
            <div className="flex items-center justify-between gap-1 text-xs bg-gray-50 border border-gray-200 rounded px-2 py-1.5">
              <span className="truncate">📎 {row[f.key].name}</span>
              {canEditFiles && (
                <button
                  type="button"
                  onClick={() => handleFileSelect(idx, f, null)}
                  className="text-red-500 hover:text-red-700 shrink-0"
                  aria-label={`Remove ${f.label}`}
                >
                  ✕
                </button>
              )}
            </div>
          ) : canEditFiles ? (
            <input
              type="file"
              accept={f.accept}
              onChange={(e) => {
                handleFileSelect(idx, f, e.target.files[0] || null);
                e.target.value = '';
              }}
              className="text-xs w-full"
            />
          ) : (
            <span className="text-gray-300 text-xs">-</span>
          )}
          {(rejection || error) && <p className="text-[11px] text-red-500 mt-0.5">{rejection || error}</p>}
        </div>
      );
    }

    return (
      <div>
        <input
          type={f.type || 'text'}
          required={f.required}
          value={row[f.key] || ''}
          placeholder={f.placeholder || ''}
          maxLength={f.maxLength}
          inputMode={f.inputMode}
          list={f.suggestions ? `${f.key}-suggestions-${idx}` : undefined}
          onChange={(e) => updateCell(idx, f.key, e.target.value)}
          onBlur={() => markTouched(idx, f.key)}
          className={`w-full border rounded px-2 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-primary-500 ${inputBorder}`}
        />
        {f.suggestions && (
          <datalist id={`${f.key}-suggestions-${idx}`}>
            {f.suggestions.map((s) => (
              <option key={s} value={s} />
            ))}
          </datalist>
        )}
        {error && <p className="text-[11px] text-red-500 mt-0.5">{error}</p>}
      </div>
    );
  }

  // Read-only mode (request details / staff review pages) keeps the classic
  // one-row-per-driver table - no inputs, so horizontal scrolling is fine.
  if (readOnly) {
    return (
      <div className="border border-gray-200 rounded-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full text-sm">
            <thead className="bg-gray-50 text-gray-600">
              <tr>
                {visibleFields.map((f) => (
                  <th key={f.key} className="px-3 py-2 text-left font-medium whitespace-nowrap">
                    {f.label}
                    {f.required && <span className="text-red-500">*</span>}
                  </th>
                ))}
                {hasDriverStatus && <th className="px-3 py-2 text-left font-medium whitespace-nowrap">Request Status</th>}
                {hasChangeSummaries && <th className="px-3 py-2 text-left font-medium whitespace-nowrap">Changes</th>}
              </tr>
            </thead>
            <tbody>
              {drivers.length === 0 && (
                <tr>
                  <td
                    colSpan={visibleFields.length + (hasDriverStatus ? 1 : 0) + (hasChangeSummaries ? 1 : 0)}
                    className="text-center text-gray-400 py-8"
                  >
                    No data to display
                  </td>
                </tr>
              )}
              {drivers.map((row, idx) => (
                <tr key={idx} className="border-t border-gray-100 align-top">
                  {visibleFields.map((f) => (
                    <td key={f.key} className="px-3 py-2">
                      <span className="whitespace-nowrap">
                        {f.type === 'file' ? row[f.key]?.name || '-' : row[f.key] || f.defaultValue || '-'}
                      </span>
                    </td>
                  ))}
                  {hasDriverStatus && (
                    <td className="px-3 py-2 whitespace-nowrap">
                      <span className="px-2 py-0.5 rounded-full text-xs bg-orange-100 text-orange-700">
                        {row.driverStatus || '-'}
                      </span>
                    </td>
                  )}
                  {hasChangeSummaries && (
                    <td className="px-3 py-2 text-xs text-gray-600 max-w-xs">
                      {row.changeSummary || <span className="text-gray-300">No changes</span>}
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    );
  }

  // Editable mode: compact summary row (name / email / phone) with the full
  // set of remaining fields always shown directly beneath it.
  const totalCols = 1 + summaryFields.length + 1; // # + summary + remove

  return (
    <div className="border border-gray-200 rounded-lg overflow-hidden">
      <div className="flex justify-end gap-2 bg-gray-50 px-4 py-2 border-b border-gray-200">
        <button
          type="button"
          onClick={removeAll}
          disabled={!drivers.length}
          className="text-sm px-3 py-1.5 rounded-md border border-gray-300 text-gray-600 disabled:opacity-40 hover:bg-gray-100"
        >
          Remove All
        </button>
        <button
          type="button"
          onClick={addRow}
          disabled={drivers.length >= MAX_DRIVERS}
          className="text-sm px-3 py-1.5 rounded-md bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-40"
        >
          + Add Driver
        </button>
      </div>
      <p className="text-xs text-gray-500 px-4 pt-3">
        Username will be assigned automatically by AD in the format{' '}
        <span className="font-medium">firstname.lastname@asmo.com</span>.
      </p>
      <table className="w-full text-sm table-fixed">
        <thead className="bg-gray-50 text-gray-600">
          <tr>
            <th className="px-3 py-2 text-left w-10">#</th>
            {summaryFields.map((f) => (
              <th key={f.key} className={`px-3 py-2 text-left font-medium ${f.fixed ? 'w-32' : ''}`}>
                {f.label}
                {f.required && <span className="text-red-500">*</span>}
              </th>
            ))}
            <th className="px-3 py-2 w-10" />
          </tr>
        </thead>
        <tbody>
          {drivers.length === 0 && (
            <tr>
              <td colSpan={totalCols} className="text-center text-gray-400 py-8">
                No data to display
              </td>
            </tr>
          )}
          {drivers.map((row, idx) => (
            <Fragment key={idx}>
              <tr className="border-t border-gray-100 align-top">
                <td className="px-3 py-2.5 text-gray-400">{idx + 1}</td>
                {summaryFields.map((f) => (
                  <td key={f.key} className="px-2 py-1.5">
                    {renderInput(idx, f, row)}
                  </td>
                ))}
                <td className="px-3 py-2">
                  <button
                    type="button"
                    onClick={() => removeRow(idx)}
                    className="text-red-500 hover:text-red-700"
                    aria-label="Remove row"
                  >
                    ✕
                  </button>
                </td>
              </tr>
              <tr className="border-t border-gray-100">
                <td colSpan={totalCols} className="bg-gray-50/70 px-6 py-4">
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-x-6 gap-y-4">
                    {detailFields.map((f) => (
                      <div key={f.key}>
                        <label className="block text-xs font-medium text-gray-600 mb-1">
                          {f.label}
                          {f.required && !f.fixed && <span className="text-red-500">*</span>}
                        </label>
                        {renderInput(idx, f, row)}
                      </div>
                    ))}
                  </div>
                </td>
              </tr>
            </Fragment>
          ))}
        </tbody>
      </table>
    </div>
  );
}
